### ISSUE TITLE
Rendertron closeBrowser: true issues when multiple request comes at same time

### ISSUE THREAD

**Issue by Sumon-TWeb** [GoogleChrome/rendertron#569] opened 2020-12-22 10:01 UTC
### **Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.**

I am try to implement rendertron in Angular site, so i have to make closeBrowser to true, else it returns **response does not exist**
This two error comes, when subsequent request comes to the rendertron server. It seems like browser is closed at the middle of an request execution, so all the request to the server is not treated as a separate process? If i make request one by one then there is no issue.
**Please have a look on this. thank you**

**Comment by dwsmart** [comment] 2020-12-22 11:34
Hi @Sumon-TWeb,

Can you provide some example URLs where you are seeing this behaviour?

**Comment by otoming** [comment] 2020-12-22 22:08
Exactly same behaviour here:
Without "closeBrowser:true": response does not exist.
With "closeBrowser:true": Error: Navigation failed because browser has disconnected!
Reproducible even with https://render-tron.appspot.com/
https://drive.google.com/file/d/1PovresdwMX7ifyfVPUEDK0SK0V_fYKWA/view

p.s. Works without issues on rendertron@3.0

**Comment by Sumon-TWeb** [comment] 2020-12-23 05:01
<img width="521" alt="Untitled" src="https://user-images.githubusercontent.com/61141437/102961156-a3334300-4509-11eb-9d27-6d35200d40c8.png">
As you can see, in the attached image two request comes almost same time, after serialization **only one request served as 200, other got error**. It is SPA angular application, so i have put closeBrowser to true.
Thanks.

**Comment by dwsmart** [comment] 2021-01-12 14:33
Hey @Sumon-TWeb 

Did you change something in the example? This seems to work ok on a local install from the current main branch for me, are you still getting errors your side? (looks like you have made some local changes, perhaps just for logging?, reading the screenshot

**Comment by farablanco** [comment] 2021-01-14 02:31
Hi, I am getting the exact same issue. I get a 400 error (response does not exist) when closeBrowser = true; and a 500 (navigation failed because the browser has disconnected) when closeBrowser = false. Used v3 as suggested by otoming and it did work.

**Comment by AVGP** [comment] 2021-01-26 18:18
I was just looking into this and it seems to be undocumented behaviour with service workers. This only happens when request interception is enabled. I assume that request interception causes a race condition to be more prevalent, where the first request arriving installs and runs the service worker and the second requests gets the response from said service worker, somehow making `page.goto` return a falsy response value.

I have created a pull request that, once landed, will be part of the 3.2.0 release.

**Comment by ygorth** [comment] 2021-02-09 03:26
I had to rollback all my environments to version 3.0.0. I was facing the issue reported by @Sumon-TWeb, after rollback I have my 200's back. Please check how it was looking like during version 3.1.0. In my case closeBrowser was false.

![rendertron](https://user-images.githubusercontent.com/1129310/107311590-97b9be00-6a5c-11eb-8655-b22a12b08107.png)

**Comment by mikeooi** [comment] 2021-06-13 16:47
> I had to rollback all my environments to version 3.0.0. I was facing the same errors reported by @Sumon-TWeb, which in my case generated a lot of 500 responses from Rendertron. After rollback I got my environment back to normal.
> 
> Please check below how it was looking like during version 3.1.0. In my case closeBrowser was false.
> 
> ![rendertron](https://user-images.githubusercontent.com/1129310/107311590-97b9be00-6a5c-11eb-8655-b22a12b08107.png)

I've rolled back to 3.0.0 using 'git reset --hard 8951beb' but when I run npm install the output is very different and does not end in success:

![image](https://user-images.githubusercontent.com/39960963/121815591-28a0e000-cc6f-11eb-8b21-5354c525d476.png)

![image](https://user-images.githubusercontent.com/39960963/121815641-60a82300-cc6f-11eb-82c9-23d920d086d5.png)

**Comment by mikeooi** [comment] 2021-06-13 17:26
> > I had to rollback all my environments to version 3.0.0. I was facing the same errors reported by @Sumon-TWeb, which in my case generated a lot of 500 responses from Rendertron. After rollback I got my environment back to normal.
> > Please check below how it was looking like during version 3.1.0. In my case closeBrowser was false.
> > ![rendertron](https://user-images.githubusercontent.com/1129310/107311590-97b9be00-6a5c-11eb-8655-b22a12b08107.png)
> 
> I've rolled back to 3.0.0 using 'git reset --hard [8951beb](https://github.com/GoogleChrome/rendertron/commit/8951beb3890b44a479676f128eb4c77857db6d8c)' but when I run npm install the output is very different and does not end in success:
> 
> ![image](https://user-images.githubusercontent.com/39960963/121815591-28a0e000-cc6f-11eb-8b21-5354c525d476.png)
> 
> npm run start:
> 
> ![image](https://user-images.githubusercontent.com/39960963/121815641-60a82300-cc6f-11eb-82c9-23d920d086d5.png)
> 
> Any idea what I've done wrong / what the problem is?

Fixed - Needed to downgrade node to 10

**Comment by ByJacob** [comment] 2021-06-14 08:52
I think this MR resolve problem:
https://github.com/GoogleChrome/rendertron/pull/596

**Closed** 2022-10-06 08:00 UTC
Labels: bug, pr pending
