### ISSUE TITLE
Express middleware only renders the index page of angular site.

### ISSUE THREAD

**Issue by AndroidLibrariesYoutube** [GoogleChrome/rendertron#282] opened 2019-03-21 17:59 UTC
I am using node and express as a backend and angular 7 as a front-end. I have added the rendertron express middleware but only index page is rendering. I have tested with multiple user-agent and the result is the same. I am unable to debug what's the problem is. Please help.

**Comment by AVGP** [comment] 2019-09-09 13:27
Duplicate of #278

**Closed by AVGP** 2019-09-09 13:27 UTC
