### ISSUE TITLE
Some pages can't load

### ISSUE THREAD

**Issue by paales** [GoogleChrome/rendertron#159] opened 2018-01-10 16:44 UTC
When trying to load our homepage we're getting the following error (online version doesn't load either)

```
{ Error: The value of property "payload" is longer than 1048487 bytes.
    at /Users/paulhachmang/Sites/reachdigital.nl/rendertron/node_modules/grpc/src/client.js:554:15 code: 3, metadata: Metadata { _internal_repr: {} } }
```

This happens when I try to load it prpl server, but doesn't happen when I access an URL directly. Not sure how the request differs (no idea how I should debug something like that)

**Comment by samuelli** [comment] 2018-01-16 19:10
Hey @paales,

Are you able to provide any reproduction steps? It's hard to help here without additional info.

Thanks.

**Comment by skullerj** [comment] 2018-01-18 23:15
Hey @paales,

I had the same issue and solved it by disabling caching on **config.json**. I can't understand exactly why this happens but I guess there is some problem with the amount of data you send to the Google Cloud Datastore, which apparently uses **grpc**.

**Comment by paales** [comment] 2018-01-26 14:11
@samuelli Yes I'm able to reproduce the error: Try load this page with a googlebot user agent: https://reachdigital.nl/magento-2/magento-2-community-webshop

I'm getting the above error, rendertron actually fetches the information correctly it if you access it directly: 
https://reach-digital-bot.appspot.com/render/https://reachdigital.nl/magento-2/magento-2-community-webshop?wc-inject-shadydom=true

But if the prpl server is fetching the information the above error is thrown on rendertron.

Prpl server also gives an error (but that is logical): `[rendertron middleware] ECONNREFUSED error fetching http://127.0.0.1:3000/render/http%3A%2F%2F127.0.0.1%3A8080%2Fmagento-2%2Fmagento-2-community-webshop?wc-inject-shadydom=true`

**Comment by samuelli** [comment] 2018-02-02 00:19
Hi @paales,

I'm unable to reproduce.

Running `curl https://reachdigital.nl/magento-2/magento-2-community-webshop -A 'googlebot'` works for me. Size looks correct to me too. ~300KB raw, ~34KB GZIP.

Closing as it seems it works? Feel free to reopen/comment that its still broken.

**Closed by samuelli** 2018-02-02 00:19 UTC

**Comment by paales** [comment] 2018-02-02 12:50
Have you tried running it through the middleware?

Loading the page via the above rendertron URL, everything works as expected, but if I run it through the middleware I'm getting the error.

**Comment by samuelli** [comment] 2018-02-02 18:49
Does the curl request I pasted above not execute through the middleware?

**Comment by paales** [comment] 2018-02-09 13:41
@samuelli You're right, i've had to disable all caching on the online environment, which makes sure it works. Was just trying to get it to work on render-tron.appspot.com, but that whole service seems to be offline :(

https://render-tron.appspot.com/render/https://reachdigital.nl/magento-2/magento-2-community-webshop?wc-inject-shadydom=true http://cloud.h-o.nl/pQNY
