### ISSUE TITLE
Continues loading on Nuxt if timeout set to zero

### ISSUE THREAD

**Issue by iranagame** [GoogleChrome/rendertron#599] opened 2021-01-30 16:35 UTC
I have setup latest rendertron as a proxy behind my NGINX server, my PWA application which is created via Nuxt usually takes 1~2 seconds to load & render completely  on my computer browser, but if I remove timeout budget value on rendertron then it will never get loaded and serialized.

However, with default timeout (10 seconds) my request always reach the budget no matter if its set to 10 seconds or 100 seconds, always reach this value and few milliseconds after that it will render & serialized!
Here is my config:
```
{
    "host": "127.0.0.1",
    "port": "3333",
    "timeout": 0,
    "closeBrowser": true,
    "cache": "filesystem",
    "cacheConfig": {
        "cacheDurationMinutes": 10080,
        "cacheMaxEntries": 1000
    }
}

```

My current workaround to get it work and speed up the page rendering is to set timeout budget as low as possible (4 seconds for instance) and request will load successfully almost on:

```
  <-- GET /render/https://xxxx.yyy/zzz 200
TimeoutError: Navigation timeout of 4000 ms exceeded
    at /home/rendertron/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
  --> GET /render/https://xxxx.yyy/zzz 200 4,609ms 679.93kb
```

**Comment by dwsmart** [comment] 2021-01-30 18:32
Hi @iranagame 

Kind of beside the point you are raising, but interested why you are using rendertron instead of nuxt's SSR features?

**Comment by iranagame** [comment] 2021-01-30 21:21
@dwsmart We are migrating to SSR but it's a very big project and need many changes since the site already wrote for PWA proposes; In the meantime we need to fill the SEO gap through rendertron somehow!

**Comment by AVGP** [comment] 2021-02-09 14:06
Does this happen with an out-of-the-box nuxt demo app, too?
I'm asking because it would help us to reproduce and debug the issue

**Comment by AVGP** [comment] 2021-03-16 14:06
I'm closing this for now as I haven't been able to reproduce this issue. If you have additional insights, feel free to comment / reopen this issue.

**Closed by AVGP** 2021-03-16 14:06 UTC
Labels: needs clarification
